"""add claimed_at to reminders

Revision ID: 88b342c70c0e
Revises: dc0f4171b77c
Create Date: 2026-07-12 17:47:33.949411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b342c70c0e'
down_revision: Union[str, None] = 'dc0f4171b77c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'claimed_at')
    # ### end Alembic commands ###
